[package]
authors = ["The Rust Project Developers"]
build = "build.rs"
name = "alloc-jemalloc"
version = "0.0.0"

[build-dependencies]
gcc = "0.3.41"

[dependencies.libc]
version = "0.2.18"
default-features = false

[features]
debug = []
